server:
  servlet:
    context-path: /BookStore

application:
  name: Book Store
  jwtSecret: RamBookStore
  jwtExpirationMs: 120000
# Expiration time: 1 Hour (1Hr * 60mins * 60sec * 1000millisec) = 120000 
 
spring:
  profiles: 
    active: dev  
   

---  

server:
  profiles: dev
  port: '8080'
spring:
  profiles: dev
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bookStore?currentSchema=dev
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: college

---

server:
  profiles: prod
  port: '8081'
spring:
  profiles: prod
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bookStore?currentSchema=prod
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: collegeProd
